import { Link } from 'react-router-dom'
import './About.css'
import Footer from './Footer'

function About() {
  return (
    <div className="page">
      <header className="page-header">
        <h1>About</h1>
        <Link to="/" className="back-link">← Back to Home</Link>
      </header>

      <section className="page-section">
        <h2>What is YC-or-not-YC?</h2>
        <p>
          YC-or-not-YC is a tool that uses AI to evaluate whether your startup idea
          would have been likely to make it into a Y Combinator batch. It analyzes your
          idea description and compares it against the descriptions of companies accepted
          into previous YC batches.
        </p>
      </section>

      <section className="page-section">
        <h2>How does it work?</h2>
        <p>
          Simply describe your startup idea in the text area on the home page, select a
          YC batch for comparison, and click "Check My Idea". The tool will return a
          verdict (Yes, No, or Maybe) along with a confidence score and probability
          breakdown.
        </p>
      </section>

      <section className="page-section">
        <h2>Disclaimer</h2>
        <p>
          This tool is for entertainment and educational purposes only. The results are
          generated by AI and should not be taken as definitive advice. Y Combinator's
          selection process considers many factors beyond just the idea itself, including
          the founding team, market timing, execution ability, and more. A "Yes" verdict
          does not guarantee acceptance, and a "No" verdict does not mean your idea isn't
          worth pursuing.
        </p>
      </section>

      <section className="page-section">
        <h2>Technology</h2>
        <p>
          YC Idea Checker is built with React and TypeScript on the frontend, with a
          Node.js/Express backend which queries the <a href="https://github.com/yc-oss/api" target="_blank">YC OSS API</a> and then uses <a href="https://typesafe.ai" target="_blank">Jev</a> to generate predictions.
        </p>
      </section>

      <Footer />
    </div>
  )
}

export default About
